/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.AlunoController;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.AlunoDAO;
import model.Refeicao;
import model.RefeicaoDAO;

/**
 *
 * @author Renan Rodrigues
 */
public class GUI_Refeicoes extends javax.swing.JFrame {
    DefaultTableModel table = new DefaultTableModel();
    DefaultTableModel table2 = new DefaultTableModel();
    /**
     * Creates new form GUI_Refeicoes
     */
    public GUI_Refeicoes() throws IOException {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        startTableRefeicao();
        startTableAlunos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableRefeicao = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRefeicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableRefeicao);
        if (jTableRefeicao.getColumnModel().getColumnCount() > 0) {
            jTableRefeicao.getColumnModel().getColumn(0).setResizable(false);
            jTableRefeicao.getColumnModel().getColumn(1).setResizable(false);
            jTableRefeicao.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel5.setText("Refeições");

        jLabel6.setText("Alunos");

        jButton3.setText("Excluir Refeição");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Créditos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableAlunos);
        if (jTableAlunos.getColumnModel().getColumnCount() > 0) {
            jTableAlunos.getColumnModel().getColumn(0).setResizable(false);
            jTableAlunos.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton4.setText("Adicionar Refeição");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aluno", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jTableAlunos.getSelectedRow() != -1){    
            Refeicao refeicao = new Refeicao();
            RefeicaoDAO rDao = new RefeicaoDAO();
            AlunoController ac = new AlunoController();
            int id;

            ArrayList<Refeicao> listRefeicao = new ArrayList();
            try {
                listRefeicao = rDao.getListRefeicao();
            } catch (IOException ex) {
                Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            if(listRefeicao.size() != 0) {
                id = listRefeicao.get(listRefeicao.size()-1).getId()+1;
            } else {
                id = 0;
            }

            int idUsuario = Integer.parseInt(jTableAlunos.getModel().getValueAt(jTableAlunos.getSelectedRow(), 0).toString());
            refeicao.setId(id);
            refeicao.setIdUsuario(idUsuario);
            refeicao.setData(LocalDateTime.now());

            rDao.insertRefeicao(refeicao, true);

            AlunoDAO aDao = new AlunoDAO();
            try {
                ac.updateCredito(1, 0, aDao.getAlunoById(idUsuario));
            } catch (IOException ex) {
                Logger.getLogger(GUI_Refeicoes.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                startTableRefeicao();
            } catch (IOException ex) {
                Logger.getLogger(GUI_Refeicoes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                startTableAlunos();
            } catch (IOException ex) {
                Logger.getLogger(GUI_Refeicoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTableRefeicao.getSelectedRow() != -1){
            int id = Integer.parseInt(jTableRefeicao.getModel().getValueAt(jTableRefeicao.getSelectedRow(), 0).toString());

            RefeicaoDAO rDao = new RefeicaoDAO();
            try {
                rDao.deleteRefeicao(id);
            } catch (IOException ex) {
                Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                startTableRefeicao();
            } catch (IOException ex) {
                Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    public void startTableAlunos() throws IOException {
        table = (DefaultTableModel) jTableAlunos.getModel();
        table.setRowCount(0);
        
        AlunoDAO aDao = new AlunoDAO();
        ArrayList<Aluno> listAluno = aDao.getListAluno();

        for(int posicaoLinha=0; posicaoLinha<listAluno.size(); posicaoLinha++){
            Aluno a = new Aluno();
            
            a.setId(listAluno.get(posicaoLinha).getId());
            a.setNome(listAluno.get(posicaoLinha).getNome());
            a.setRa(listAluno.get(posicaoLinha).getRa());
            a.setSenha(listAluno.get(posicaoLinha).getSenha());
            a.setQtdCreditos(listAluno.get(posicaoLinha).getQtdCreditos());
            
            table.insertRow(posicaoLinha, new Object[]{a.getId(), a.getNome(),a.getQtdCreditos()});
        }
    }
    
    public void startTableRefeicao() throws IOException {
        table2 = (DefaultTableModel) jTableRefeicao.getModel();
        table2.setRowCount(0);
        
        RefeicaoDAO rDao = new RefeicaoDAO();
        AlunoDAO aDao = new AlunoDAO();
        
        ArrayList<Refeicao> listRefeicao = rDao.getListRefeicao();

        for(int posicaoLinha=0; posicaoLinha<listRefeicao.size(); posicaoLinha++){
            Refeicao r = new Refeicao();
            Aluno a = new Aluno();
            
            r.setId(listRefeicao.get(posicaoLinha).getId());
            r.setIdUsuario(listRefeicao.get(posicaoLinha).getIdUsuario());
            r.setData(listRefeicao.get(posicaoLinha).getData());
            
            a = aDao.getAlunoById(listRefeicao.get(posicaoLinha).getIdUsuario());
            
            System.out.println("Funciona");
            
            table2.insertRow(posicaoLinha, new Object[]{r.getId(), a.getNome(), r.getData().toString()});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Refeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Refeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Refeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Refeicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_Refeicoes().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GUI_Refeicoes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAlunos;
    private javax.swing.JTable jTableRefeicao;
    // End of variables declaration//GEN-END:variables
}
