/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.AlunoDAO;

/**
 *
 * @author Renan Rodrigues
 */
public class GUI_Usuario extends javax.swing.JFrame {
    DefaultTableModel table = new DefaultTableModel();
    int id;
    /**
     * Creates new form CRUD_Aluno
     */
    public GUI_Usuario() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        startTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSenhaAluno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRaAluno = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));

        jLabel4.setText("Nome:");

        jLabel5.setText("Senha:");

        jLabel10.setText("RA:");

        jButton4.setText("Cadastrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "RA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAluno);
        if (jTableAluno.getColumnModel().getColumnCount() > 0) {
            jTableAluno.getColumnModel().getColumn(0).setResizable(false);
            jTableAluno.getColumnModel().getColumn(1).setResizable(false);
            jTableAluno.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Atualizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSenhaAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                    .addComponent(jTextFieldRaAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(0, 692, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldRaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aluno", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Aluno aluno = new Aluno();
        AlunoDAO aDao = new AlunoDAO();

        aluno.setId(id);
        aluno.setNome(jTextFieldNomeAluno.getText());
        aluno.setRa(jTextFieldRaAluno.getText());
        aluno.setSenha(jTextFieldSenhaAluno.getText());
        aluno.setQtdCreditos(0);

        try {
            aDao.updateAluno(aluno);
        } catch (IOException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            startTable();
        } catch (IOException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTableAluno.getSelectedRow() != -1){
            int id = Integer.parseInt(jTableAluno.getModel().getValueAt(jTableAluno.getSelectedRow(), 0).toString());

            AlunoDAO aDao = new AlunoDAO();
            try {
                aDao.deleteAluno(id);
            } catch (IOException ex) {
                Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                startTable();
            } catch (IOException ex) {
                Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunoMouseClicked
        AlunoDAO aDao = new AlunoDAO();
        Aluno aluno = new Aluno();
        ArrayList<Aluno> listAluno = new ArrayList();
        id = Integer.parseInt(jTableAluno.getModel().getValueAt(jTableAluno.getSelectedRow(), 0).toString());

        jTextFieldNomeAluno.setText(jTableAluno.getModel().getValueAt(jTableAluno.getSelectedRow(), 1).toString());
        jTextFieldRaAluno.setText(jTableAluno.getModel().getValueAt(jTableAluno.getSelectedRow(), 2).toString());

        try {
            listAluno = aDao.getListAluno();
        } catch (IOException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(listAluno != null) {
            for(int i = 0; i < listAluno.size(); i++) {
                if(id == listAluno.get(i).getId()) {
                    jTextFieldSenhaAluno.setText(listAluno.get(i).getSenha());
                    break;
                }
            }
        }
    }//GEN-LAST:event_jTableAlunoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Aluno aluno = new Aluno();
        int idAdd = 0;
        AlunoDAO alunoDao = new AlunoDAO();
        ArrayList<Aluno> listAluno = new ArrayList();
        try {
            listAluno = alunoDao.getListAluno();
        } catch (IOException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(listAluno != null) {
            if(listAluno.size() != 0) {
                idAdd = listAluno.get(listAluno.size()-1).getId()+1;
            } else {
                idAdd = 0;
            }
        }

        aluno.setId(idAdd);
        aluno.setNome(jTextFieldNomeAluno.getText());
        aluno.setRa(jTextFieldRaAluno.getText());
        aluno.setSenha(jTextFieldSenhaAluno.getText());
        aluno.setQtdCreditos(0);

        try {
            alunoDao.insertAluno(aluno, true);
        } catch (IOException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            startTable();
        } catch (IOException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void startTable() throws IOException, FileNotFoundException, ClassNotFoundException {
        AlunoDAO aDao = new AlunoDAO();
        ArrayList<Aluno> listAluno = aDao.getListAluno();
        
        if(listAluno != null) {
            table = (DefaultTableModel) jTableAluno.getModel();
            table.setRowCount(0);

            for(int posicaoLinha=0; posicaoLinha<listAluno.size(); posicaoLinha++){
                Aluno a = new Aluno();

                a.setId(listAluno.get(posicaoLinha).getId());
                a.setNome(listAluno.get(posicaoLinha).getNome());
                a.setRa(listAluno.get(posicaoLinha).getRa());
                a.setSenha(listAluno.get(posicaoLinha).getSenha());
                a.setQtdCreditos(listAluno.get(posicaoLinha).getQtdCreditos());

                table.insertRow(posicaoLinha, new Object[]{a.getId(), a.getNome(),a.getRa()});
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI_Usuario().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GUI_Usuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAluno;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldRaAluno;
    private javax.swing.JTextField jTextFieldSenhaAluno;
    // End of variables declaration//GEN-END:variables
}
